runs on my machine

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -eu -o pipefail
+
 # this is the entrypoint for development. It wraps up compiling and calling dev.ts
 # all arguments, changes, etc. should be found in src/dev.ts
 
@@ -7,7 +9,7 @@
 
 # check node exists
 if ! which node > /dev/null ; then
-	echo "node not found on the system install version in .nvmrc based on instructions in README"
+	echo "node not found on the system. Install version in .nvmrc based on instructions in README"
 	exit 1
 fi
 
