Add detect-secrets to precommit hook, prepare to open source.  (#668)
* Add detect-secrets to precommit hook

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -28,6 +28,12 @@ if ! which yarn > /dev/null ; then
 	exit 1
 fi
 
+# check lerna exists
+if ! which lerna > /dev/null ; then
+	echo "lerna not found on the system. On macOS, you can install it with 'brew install lerna'"
+	exit 1
+fi
+
 # check serverless is installed globally.
 if ! which serverless > /dev/null ; then
 	echo "installing serverless globally"
